codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project: false
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
