import org.gradle.api.JavaVersion

const val kotlinVersion = "1.7.20-RC"
const val kotlinLoggingVersion = "1.6.26"
const val coroutinesVersion = "1.5.0"
const val ktorVersion = "1.6.4"
const val ktorSpaVersion = "1.2.1"
const val ktorOpenApiGeneratorVersion = "0.2-beta.13"
const val kotlinxSerializationVersion = "1.2.2"
const val koinVersion = "2.0.1"
const val mockkVersion = "1.12.8"
const val exposedVersion = "0.26.1"
const val sqliteVersion = "3.28.0"
const val log4jVersion = "2.17.1"
const val grpcVersion = "1.49.0"
const val protobufVersion = "3.21.1"
const val protobufPluginVersion = "0.8.19"
const val slf4jVersion = "1.7.30"
const val testcontainersVersion = "1.14.1"
const val kotestAssertionsCoreVersion = "4.3.2"
const val commonsLang3Version = "3.8.1"
const val junit4Version = "4.12"
const val hikariCPVersion = "3.3.1"
const val gsonVersion = "2.8.2"
const val JCDPVersion = "2.0.3.1"
const val guavaVersion = "26.0-jre"
const val commonsCliVersion = "1.4"
const val jacksonDatabindVersion = "2.9.3"
